"""Crash-resistant high-fidelity collision backend for MuJoCo exports.

CoACD is useful, but its native library can hit a C++ assertion on some CAD
triangle soups.  On Windows that assertion opens a modal CRT dialog inside the
web-server process, so a browser export appears to hang forever and Python
``try/except`` cannot recover it.

The project already ships ``vhacdx`` as a core dependency.  This compatibility
layer adds a ``vhacd`` collision mode to the shared ROS mesh converter and makes
that mode the normal MJCF default.  V-HACD still represents a concave CAD part
as a union of convex meshes (which is what MuJoCo needs), but it avoids the
CoACD DLL that caused the web-export assertion.

If V-HACD raises a normal Python exception for an individual source mesh, only
that mesh falls back to one convex hull so the package still exports.  Explicit
advanced callers can still request the legacy CoACD path by passing
``allow_native_coacd=True`` together with ``collision='coacd'``.
"""

from __future__ import annotations

import hashlib
import json
import os
from functools import wraps

_VHACD_CACHE_VERSION = 1
_VHACD_MODE = "vhacd"

_VHACD_PRESETS = {
    "balanced": {
        "maxConvexHulls": 32,
        "resolution": 250000,
        "minimumVolumePercentErrorAllowed": 1.0,
        "maxRecursionDepth": 10,
        "shrinkWrap": True,
        "fillMode": "flood",
        "maxNumVerticesPerCH": 64,
        "asyncACD": True,
        "minEdgeLength": 2,
        "findBestPlane": False,
    },
    "fine": {
        "maxConvexHulls": 64,
        "resolution": 500000,
        "minimumVolumePercentErrorAllowed": 0.5,
        "maxRecursionDepth": 12,
        "shrinkWrap": True,
        "fillMode": "flood",
        "maxNumVerticesPerCH": 64,
        "asyncACD": True,
        "minEdgeLength": 2,
        "findBestPlane": False,
    },
}


def _cache_key(src, quality, params):
    with open(src, "rb") as f:
        h = hashlib.sha1(f.read())
    h.update(json.dumps(
        ["vhacd", quality, params, _VHACD_CACHE_VERSION],
        sort_keys=True,
    ).encode("utf-8"))
    return h.hexdigest()


def _cached_parts(directory):
    marker = os.path.join(directory, "DONE")
    if not os.path.isfile(marker):
        return None
    names = sorted(
        (name for name in os.listdir(directory)
         if name.startswith("part_") and name.endswith(".stl")),
        key=lambda value: int(value[5:-4]),
    )
    if not names:
        return None
    try:
        return [open(os.path.join(directory, name), "rb").read() for name in names]
    except OSError:
        return None


def _write_cache(directory, parts):
    os.makedirs(directory, exist_ok=True)
    for index, data in enumerate(parts):
        path = os.path.join(directory, f"part_{index}.stl")
        tmp = path + ".tmp"
        with open(tmp, "wb") as f:
            f.write(data)
        os.replace(tmp, path)
    marker = os.path.join(directory, "DONE")
    with open(marker + ".tmp", "w", encoding="utf-8") as f:
        f.write(str(len(parts)))
    os.replace(marker + ".tmp", marker)


def _vhacd_part_stls(src, quality, cache_dir):
    """Return convex STL parts generated by V-HACD, with a safe hull fallback."""
    from . import ros_export as ros

    quality = quality if quality in _VHACD_PRESETS else "fine"
    params = dict(_VHACD_PRESETS[quality])
    directory = os.path.join(
        cache_dir, "vhacd", _cache_key(src, quality, params)[:24])
    cached = _cached_parts(directory)
    if cached:
        return cached

    try:
        import numpy as np
        import trimesh
        from vhacdx import compute_vhacd

        mesh = ros._load_mesh_metres(src)
        vertices = np.asarray(mesh.vertices, dtype=np.float64)
        triangles = np.asarray(mesh.faces, dtype=np.uint32)
        if len(vertices) < 4 or len(triangles) < 4:
            raise ValueError("too few vertices/faces for convex decomposition")

        # vhacdx follows VTK's polygon stream convention: each triangle is
        # encoded as [3, i0, i1, i2].
        faces = np.column_stack((
            np.full(len(triangles), 3, dtype=np.uint32),
            triangles,
        )).ravel()

        try:
            outputs = compute_vhacd(vertices, faces, **params)
        except TypeError:
            # Older vhacdx releases exposed no keyword tuning.  They are still
            # preferable to sending the crash-prone CoACD DLL through Web UI.
            outputs = compute_vhacd(vertices, faces)

        parts = []
        for part_vertices, part_faces in outputs:
            part = trimesh.Trimesh(
                vertices=part_vertices,
                faces=part_faces,
                process=True,
                validate=True,
            )
            if len(part.vertices) < 4 or len(part.faces) < 4:
                continue
            # V-HACD should already be convex.  Re-hulling each result removes
            # any numerical non-convexity before MuJoCo sees it.
            part = part.convex_hull
            part.units = "meter"
            parts.append(part.export(file_type="stl"))

        if not parts:
            raise ValueError("V-HACD returned no usable convex parts")
        try:
            _write_cache(directory, parts)
        except OSError:
            pass
        return parts
    except Exception as exc:
        # A bad CAD tessellation must not make the entire package impossible to
        # export.  This fallback is conservative but keeps the server alive.
        print(
            f"[sw2robot.mjcf] V-HACD failed for {os.path.basename(src)}: "
            f"{type(exc).__name__}: {exc}; falling back to one convex hull")
        return ros._hull_part_stls(src)


def _safe_mjcf_kwargs(kwargs):
    """Choose V-HACD for ordinary MJCF calls and keep CoACD explicitly opt-in."""
    out = dict(kwargs)
    allow_native_coacd = bool(out.pop("allow_native_coacd", False))

    # This wrapper sits outside mjcf_validation_defaults.  Turning off that
    # wrapper's strict flag prevents it from rewriting the chosen backend to
    # CoACD.  V-HACD is then threaded through the existing ROS->MJCF mesh path.
    if "strict_mesh_collision" not in out:
        out["strict_mesh_collision"] = False

    requested = out.get("collision")
    if requested == "coacd" and not allow_native_coacd:
        out["collision"] = _VHACD_MODE
    elif requested is None:
        out["collision"] = _VHACD_MODE

    # The shared API already carries coacd_quality; reuse its two user-facing
    # quality labels for V-HACD without adding another Web setting.
    out.setdefault("coacd_quality", "fine")
    return out


def install():
    """Install the V-HACD mesh mode and make it the outermost MJCF default."""
    from . import mjcf_export as mjcf
    from . import ros_export as ros

    if getattr(mjcf, "_vhacd_safe_default_installed", False):
        return

    if _VHACD_MODE not in ros.COLLISION_MODES:
        ros.COLLISION_MODES = tuple(ros.COLLISION_MODES) + (_VHACD_MODE,)

    original_collision_parts = ros._collision_part_stls

    @wraps(original_collision_parts)
    def collision_part_stls(src, mode, quality, cache_dir):
        if mode == _VHACD_MODE:
            return _vhacd_part_stls(src, quality, cache_dir)
        return original_collision_parts(src, mode, quality, cache_dir)

    ros._collision_part_stls = collision_part_stls

    original_write = mjcf.write_mjcf_package
    original_build = mjcf.build_mjcf_package

    @wraps(original_write)
    def write_mjcf_package(*args, **kwargs):
        return original_write(*args, **_safe_mjcf_kwargs(kwargs))

    @wraps(original_build)
    def build_mjcf_package(*args, **kwargs):
        return original_build(*args, **_safe_mjcf_kwargs(kwargs))

    mjcf.write_mjcf_package = write_mjcf_package
    mjcf.build_mjcf_package = build_mjcf_package
    mjcf._vhacd_safe_default_installed = True
